### ISSUE TITLE
Error: afs: invalid call for m_streamsts.get_duration

### ISSUE THREAD

**Issue by quamt** [rigaya/VCEEnc#10]
When converting a file with the below command:
`VCEEncC64 --avhw --interlace bff --vpp-afs preset=anime --audio-codec aac -i "M.mkv" -c avc -u fast -o "M_enc.mkv" --log log.txt`

The following error pops up:

`afs: invalid call for m_streamsts.get_duration(98616).
Error while running filter "afs".
Failed to filter frame.`

So far this is the only file this happened.

Running the file through NVCencC64 works fine and no error pos up and the file is complete.

The error occurs near the end of the file basically 2 minutes are missing and not converted.

If using pipe via FFmpeg to vccenc and using software decode there is no issue.

Is there any way to check what or where the issue is?

**Comment by rigaya** [comment]
Probably, the timestamp from the hardware decoder might be the cause, as there is no problem with software decode.

We should be able to check this by adding "log=true" to --vpp-afs (like "--vpp-afs preset=anime,log=true"), and comparing the log between hardware decode and software decode.

**Comment by quamt** [comment]
@rigaya 
I compared the two files
`

iframe | sts |   | pos | orig_pts | q_jit | prevjit | pos24 | phase24 | rff_smooth
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
98615 |   |   |   | Sheet1:394460 vs Sheet2:394488 | Sheet1:394460 vs Sheet2:394488 |   |   |   |  
98616 |   |   |   | Sheet1:394464 vs Sheet2:394496 | Sheet1:394464 vs Sheet2:394496 |   |   |   |  
98617 |   |   |   | Sheet1:394468 vs Sheet2:394492 | Sheet1:394468 vs Sheet2:394492 |   |   |   |  
98618 |   |   |   | Sheet1:394472 vs Sheet2:394504 | Sheet1:394472 vs Sheet2:394504 |   |   |   |  
98619 |   |   |   | Sheet1:394476 vs Sheet2:394500 | Sheet1:394476 vs Sheet2:394500 |   |   |   |  

`

Sheet1 is software decode and hardware encode.
Sheet 2 is hardware de and encode.

After this lines the hardware decode has no more entries as it fails.

**Comment by rigaya** [comment]
Thanks for the logs, hardware decode seems to return timestamps in the wrong order (iframe = 98616 <-> 98617, 98618 <->98619), and this caused the timestamp and duration to calculation to cause error.

Also big jump between iframe = 98614 and 98615 is strange, I think hardware decoder seems to be partially crushing here, but difficult to figure out whether the app or the driver is doing some wrong...

**Comment by quamt** [comment]
If I run it through the Nvidia card via NVEncC64 there is no issue popping up.
I can upload that log after I rerun the file if needed.

**Comment by quamt** [comment]
It only happens with AMD. 
Intel and Nvidia have no issue withe the file.
I will do some more testing with older version of the AMF app an report back.

**Comment by quamt** [comment]
I will close this for now.
Remuxing the file before encoding seems to fix it for AMD too.
