### ISSUE TITLE
Hardware encoding to HEVC in 10-bits not working with Vega 8 (Ryzen 2200G Processor)

### ISSUE THREAD

**Issue by KBushido** [rigaya/VCEEnc#100]
So I have tested this with multiple video types and it always gives the same error. Seems to work fine when output depth is left default (8-bits).

Here is just a random clip from Youtube of Godzilla x Kong - The New Empire - Official Trailer.
8 bits output vs 10 bits output.

> C:\Users\KC\Desktop\VCEEncC>VCEEncC64.exe --avhw --codec hevc -i GodzillaxKong.mp4 -o  gtrailer.mkv
> --------------------------------------------------------------------------------
> gtrailer.mkv
> --------------------------------------------------------------------------------
> VCEEnc (x64) 8.21 (r1577) by rigaya, Dec 10 2023 04:01:37 (VC 1937/Win)
> OS:            Windows 10 x64 (19045) [UTF-8]
> CPU:           AMD Ryzen 3 2200G with Radeon Vega Graphics [3.70GHz] (4C/4T)
> GPU:           AMD Radeon Vega 8 [31.0.21910.5]
> AMF:           Runtime 1.4.31 / SDK 1.4.30
> Input Info:    avvce: H.264/AVC, 1920x1080, 24000/1001 fps
> Output:        H.265/HEVC  main @ Level 4 (main tier)
>                1920x1080p 1:1 23.976fps (24000/1001fps)
>                avwriter: hevc => matroska
> Quality:       balanced
> CQP:           I:22, P:24
> VBV Bufsize:   12000 kb
> Bframes:       0 frames
> Pre Analysis:  off
> Ref frames:    2 frames
> LTR frames:    0 frames
> Motion Est:    Q-pel
> Slices:        1
> GOP Len:       240 frames
> Others:        skipframe:on deblock
> 
> encoded 4047 frames, 135.14 fps, 2097.11 kbps, 42.20 MB
> encode time 0:00:29, CPU: 19.2%, GPU: 26.8%, VE: 99.1%
> frame type IDR   17
> frame type I     17,  avgQP  22.00,  total size   0.37 MB
> frame type P   4030,  avgQP  24.00,  total size  41.82 MB
> 
> C:\Users\KC\Desktop\VCEEncC>VCEEncC64.exe --avhw --codec hevc --output-depth 10 -i GodzillaxKong.mp4 -o  gtrailer2.mkv
> --------------------------------------------------------------------------------
> gtrailer2.mkv
> --------------------------------------------------------------------------------
> VCEEnc (x64) 8.21 (r1577) by rigaya, Dec 10 2023 04:01:37 (VC 1937/Win)
> OS:            Windows 10 x64 (19045) [UTF-8]
> CPU:           AMD Ryzen 3 2200G with Radeon Vega Graphics [3.70GHz] (4C/4T)
> GPU:           AMD Radeon Vega 8 [31.0.21910.5]
> AMF:           Runtime 1.4.31 / SDK 1.4.30
> Input Info:    avvce: H.264/AVC, 1920x1080, 24000/1001 fps
> VPP            cspconv(nv12 -> yv12(16bit))
>                cspconv(yv12(16bit) -> p010)
> Output:        H.265/HEVC  main @ Level 4 (main tier)
>                1920x1080p 1:1 23.976fps (24000/1001fps)
>                avwriter: hevc => matroska
> Quality:       balanced
> CQP:           I:22, P:24
> VBV Bufsize:   12000 kb
> Bframes:       0 frames
> Pre Analysis:  off
> Ref frames:    2 frames
> LTR frames:    0 frames
> Motion Est:    Q-pel
> Slices:        1
> GOP Len:       240 frames
> Others:        skipframe:on deblock
> Break in task AMFENC: unknown error..
> avout: failed to write header for output file: Invalid data found when processing input
> 
> encoded 0 frames, 0.00 fps, 0.00 kbps, 0.00 MB
> encode time 0:00:01, CPULoad: 21.5%
> Finished with error in VCEEncC.

Have the same issue in Handbrake as well.

**Comment by rigaya** [comment]
Unfortunately, Ryzen 2xxx and 3xxx APU is known to support 8bit HEVC encoding only.

Please check the table on the link below.
https://github.com/rigaya/VCEEnc#supported-hw-encode-codecs

**Comment by KBushido** [comment]
That's weird, someone linked me these on reddit. 
https://www.cpu-monkey.com/en/igpu-amd_radeon_rx_vega_8_raven_ridge
https://cpu-benchmark.org/igpus/amd-radeon-vega-8-graphics/

**Comment by rigaya** [comment]
The table I've shown should be the status of VCEEnc. As Handbrake is also the same, I believe that the table I've made in the old days is correct.

As I'm not able to test as I don't have 2xxx or 3xxx APUs now, I won't be able to go into this further.

**Comment by KBushido** [comment]
Ok, thanks and I appreciate the quick response.
