### ISSUE TITLE
Dolby Vision support

### ISSUE THREAD

**Issue by Dendraspis** [rigaya/VCEEnc#104]
Hello rigaya,

whereas the docs suggest Dolby Vision support....
https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#--dolby-vision-profile-float
https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#--dolby-vision-rpu-string

...the code disables it here completely:
https://github.com/rigaya/VCEEnc/blob/5d471f5592d5445847e630bf5659c2902ce1d79e/VCECore/rgy_version.h#L73

This leads to error messages related to the unknown parameters:
`Unknown option: --dolby-vision-profile`
`Unknown option: --dolby-vision-rpu` 

Is it turned off on purpose or are you going to enable it?

**Comment by rigaya** [comment]
I7m sorry the document is wrong here, it was miss copy pasted from NVEnc. I'll have it removed from the documents.
