### ISSUE TITLE
interlace supports now auto?

### ISSUE THREAD

**Issue by quamt** [rigaya/VCEEnc#11]
Hello,

I noticed that there seems to be now auto for the option --interlace.
Normally it only accepted bff or tff.
Wanted to check if that is new as I did not see it in the documentation.

**Comment by rigaya** [comment]
Oh, that's a mistake, VCEEnc does not support "--interlace auto", recognizing "--interlace auto" is a wrong behavior. I'll fix that in the next release.

**Comment by rigaya** [comment]
I'll close this issue as the topic has been answered.
