### ISSUE TITLE
Noticeably lower HEVC (8-bit) encode PSNR quality compared to other applications. (Other scores are also slightly lower)

### ISSUE THREAD

**Issue by DimkaTsv** [rigaya/VCEEnc#113]
Happened to do quality comparison between VCEEnc and Handbrake (i guess i wanted to repeat old experiment) with as close and simple of a parameters as possible.

Performed test on 4k60 sample. Compared source to outputs with FFMetrics PSNR/SSIM/VMAF score. And for AV1 and AVC results were as expected, VCEEnc was slightly ahead. But, for some reason, for HEVC results were not as i expected. With HEVC VCEEnc noticeably lagged behind. Especially so on PSNR score. I tested number of options that would've not broken "fair" comparison, but couldn't close this gap.

To check which encoder results were a fluke i tried to do ffmpeg encode and also compiled from AMF sources TranscodeHW command line tool (which, surprisingly, was basically ffmpeg under disguise based on output it produced). 
As result ALL OF THEM produced results noticeably higher than VCEEnc did. Meaning issue is probably on side of VCEEnc. Moreover, issue seems to be specific to 8-bit HEVC, as when i encoded with `--output-depth 10`, output had around expected PSNR score. 

I also tried old VCEEnc 8.17 version (one which i have copy just to test point scaling, fix for which still doesn't seem to be released). Same result HEVC encoded video scored lower (technically it should've been same video after all, as i used same set of parameters)

Here is screenshot with case on hand:
![image](https://github.com/user-attachments/assets/0427a725-84d8-469c-9538-d67704199470)

VCEEnc HEVC produced output with 34.6562 PSNR (Which is lower than AVC output PSNR, and that should not be like that, because AMD AVC encoder is noticeably lagging behind)
VCEEnc HEVC10 produced output with 37.538 PSNR
FFMPEG and TranscodeHW HEVC produced output with 37.2348 PSNR

VCEEnc AVC produced output with 35.8521 PSNR

Will note though, that even though VCEEnc HEVC SSIM and VMAF scores are also slightly lower than expected (for example 91 VMAF vs approx 93 on other tools), they are way less concerning unless you look closely. 

But, anyways, based on results of AV1 and AVC, VCEEnc should've produced results higher than other applications!

**Used commands:**
**Handbrake:** 
```
Video Encoder = H.265(VCE) 
Variable framerate (same as source) 
Avg bitrate = 35000 kbps
Encoder preset = Quality 
Encoder profile = Main 
Encoder level = Auto
Filters = set everything to OFF
```
**VCEEnc:** `%~dp0\VCEEncC64.exe -i %1 -o "%~n1_processed%~x1" --codec hevc --vbr 35000 --preset slow --level 6.2 --audio-copy`

**FFMPEG:** `%~dp0\ffmpeg -i %1 -hide_banner -loglevel warning -stats -hwaccel d3d11va -i %1 -map 0 -c:s copy -c:v hevc_amf -quality quality -preset quality -rc vbr_peak -b:v 35000k -c:a copy %~n1_ffmpeg.mkv`

**TranscodeHW (AMF):** `%~dp0\TranscodeHW.exe -input %1 -output "%~n1_TranscodeHW%~x1" -codec hevc -hevcprofilelevel 6.2 -hevcqualitypreset quality -hevcratecontrolmethod vbr -hevctargetbitrate 35000000`

**Comment by rigaya** [comment]
I think that some options might have different default values might have causing the issue. VCEEnc does not necessarily set the parameter default as same as AMF default.

As the implementation differs, I don't think to go deep into this, but I did some change in [VCEEnc 8.24](https://github.com/rigaya/VCEEnc/releases/tag/8.24) targeting this issue.

For example, ```--ref``` had default value of 2 for VCEEnc 8.23 or before, but AMF default was "auto" (depending on preset selected).

In [VCEEnc 8.24](https://github.com/rigaya/VCEEnc/releases/tag/8.24), I've changed default to "auto" for some options like "--ref" which AMF default is "auto", which might change the behaviour.

**Comment by DimkaTsv** [comment]
Can confirm vast improvement. It is even slightly better than AMF FFMPEG implementation. (same source file, same commands).
Here is screenshot with newer data.
*_processed = VCEEnc
*_TranscodeHW = AMF 1.4.24 ffmpeg based TranscodeHW implementation (self-compiled from source without any changes)

![image](https://github.com/user-attachments/assets/4e21b390-1834-4e0e-a003-ed271099d489)

On this note, i guess this issue is resolved.
