### ISSUE TITLE
Unable to use HEVC Profile main10

### ISSUE THREAD

**Issue by menzbua** [rigaya/VCEEnc#13]
Hi,

i try to encode an HEVC HDR Video with 10Bits of color depth. When i try to use the HEVC Profile Main10 i got an error message from the VCEEncoder that only main profile is a valid option. Is there any why to encode 10Bit Video with VCEEnc?

I'm using Windows 10 with the latest AMD drivers and an RX5700 Graphics Card.

Thanks a lot
Regards
Manuel

**Comment by rigaya** [comment]
Current AMD HW Encoders does not support 10bit HEVC encoding (even on RX5xxx), it is limited to Main profile only.

**Comment by menzbua** [comment]
Okay, thanks for the fast response.

Regards
Manuel
