### ISSUE TITLE
REQUEST: --vpp-subburn

### ISSUE THREAD

**Issue by djrooli** [rigaya/VCEEnc#14]
Hello Rigaya!

If you have spare time, can you please implement --vpp-subburn to VCEEnc?

If you do, then thank you very much in advance.

**Comment by rigaya** [comment]
--vpp-subburn has been added in [VCEEnc 6.06](https://github.com/rigaya/VCEEnc/releases/tag/6.06), please have a try.

**Comment by djrooli** [comment]
Thank you very much Rigaya!
It works great with awhw & awsw using "filename".sup

**Comment by rigaya** [comment]
Thank you for confirming, I'll close this issue now.
