### ISSUE TITLE
Green bar artifact when using --avhw at 4K

### ISSUE THREAD

**Issue by Vrael0n** [rigaya/VCEEnc#15]
I'm getting a green bar across the top of my encodes when using --avhw on 4K HEVC NVENC OBS recordings. The problem does not occur when using --avsw. At first I suspected it may be related to GTX 1xxx (Pascal) NVENC being unable to use CABAC with HEVC, however, the problem does not occur with 1080p NVENC clips so I am not sure. I have attached an image showing the artifact, and a link to the source video file I am encoding so it can be tested with other VCE hardware.

CL:
C:\Users\NAS\Downloads\VCEEncC_6.06_x64>VCEEncC64.exe --avhw --input "C:\Users\NAS\Remote\OBS Recordings\2020-11-15 18-44-45.mkv" --codec hevc --profile main --tier main -u slow --cqp 24 --colorrange auto --colormatrix auto --colorprim auto --transfer auto --audio-copy --output "C:\Users\NAS\Remote\OBS Recordings\2020-11-15 18-44-45 VCE.mkv"

Info:
VCEEnc (x64) 6.06 (r657) by rigaya, Nov  9 2020 11:56:01 (VC 1927/Win/avx2)
OS Version     Windows 10 x64 (18363)
CPU:           AMD Athlon 3000G with Radeon Vega Graphics (2C/4T)
GPU:           AMD Radeon Vega 3, AMF Runtime 1.4.17 / SDK 1.4.16
Input Info:    avvce: H.265/HEVC, 3840x2160, 60/1 fps
Vpp Filters    copyDtoD
Output:        H.265/HEVC  main @ Level 5.1 (main tier)
               3840x2160p 1:1 60.000fps (60/1fps)
               avwriter: hevc, aac => matroska
Quality:       slow
CQP:           I:24, P:24
VBV Bufsize:   40000 kbps
Bframes:       0 frames
Pre Analysis:  off
Ref frames:    2 frames
LTR frames:    0 frames
Motion Est:    Q-pel
Slices:        1
GOP Len:       600 frames
VUI:              matrix:bt709,colorprim:bt709,transfer:bt709,range:full
Others:        deblock

Source Video [556MB]: https://drive.google.com/file/d/1npWVqjoOw68mQAbDTFuabdC1yDYqiOYM/view?usp=sharing
Output Video [200MB]: https://drive.google.com/file/d/1XVlC1_NAlGaP99yIDXPedFCZzLyT431w/view?usp=sharing

Image (green bar artifact on top):
![2020-11-15 18-44-45 VCE mkv_snapshot](https://user-images.githubusercontent.com/61518774/99213205-dd2e5e00-2781-11eb-86b1-942a6c469d12.png)

**Comment by rigaya** [comment]
Thanks for the samples, I was able to reproduce the green artifact. However I'm not able to find out what is causing this issue... I'll check further from now.

**Comment by Vrael0n** [comment]
I have uninstalled, wiped, and fresh reinstalled the latest Radeon driver and the problem is gone. Can you confirm a driver update fixes it for you too?

**Comment by rigaya** [comment]
Thanks for letting me know, reinstalling the Radeon driver to the latest version fixes the problem!

I'll close this issue as the problem has been solved.
