### ISSUE TITLE
Strange 5.1 behavior for libopus and opus

### ISSUE THREAD

**Issue by quamt** [rigaya/VCEEnc#17]
Hello, when trying to convert an 5.1 audio there is some strange behavior

For libopus  it has to be defined as `--audio-codec libopus --audio-stream 5.1`
If only `--audio-codec libopus` is used the following error shows:
`[libopus @ 00000161cfc73f00] Invalid channel layout 5.1(side) for specified mapping family -1.
avout: failed to open encoder(libopus) for audio track 1: Invalid argument
failed to initialize file reader(s).`

For opus when defined as `--audio-codec opus` it will convert to a mono stream.
When  defined as `--audio-codec opus --audio-stream 5.1`
Following error shows.
`[opus @ 000002ab0f313b40] Specified channel layout '5.1' is not supported
avout: failed to open encoder(opus) for audio track 1: Invalid argument
failed to initialize file reader(s).`

It would be great if there is an auto 5.1 to 5.1 for libopus as it works for example for aac.
Not sure why opus does not support 5.1, is that some limitations or restriction?

**Comment by rigaya** [comment]
When converting into 5.1ch, would you please try options below? The output shall be written after ":".
```
--audio-codec opus --audio-stream :5.1
```

**Comment by quamt** [comment]
I tested the setting as mentioned and I get
`[opus @ 000002118d5e2b80] Specified channel layout '5.1' is not supported
avout: failed to open encoder(opus) for audio track 1: Invalid argument
failed to initialize file reader(s).`

**Comment by rigaya** [comment]
Sorry, I have mistaken the option,

--audio-codec **lib**opus --audio-stream :5.1

should work.

**Comment by quamt** [comment]
Yes the option --audio-codec libopus --audio-stream :5.1 works.
But it will turn any stream to 5.1.
For example when batch encoding if there is a stereo stream it will be converted in to 5.1.
For aac it will auto select stereo or 5.1 is that a aac specific feature?

**Comment by rigaya** [comment]
> For aac it will auto select stereo or 5.1

[--audio-stream](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#--audio-stream-intstring1string2) is not intended to be that kind of "auto" feature, it is to select a track **manually** and specify the separate/merge/conversion you need. I'm not sure why you have this "auto selection" behavior in aac.
