### ISSUE TITLE
VCEEncC_Options.ja.md 内の --preset オプションが実際には存在しない

### ISSUE THREAD

**Issue by tsukumijima** [rigaya/VCEEnc#20]
[VCEEncC_Options.ja.md](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.ja.md#%E3%81%9D%E3%81%AE%E4%BB%96%E3%81%AE%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3) には「エンコーダの品質プリセット」として `-u, --preset` オプションが定義されていますが、実際には存在しないようです（ `Error: Unknown option: --preset` とエラーが出るという報告がありました）。

同様のオプションは QSVEncC では `--quality` 、NVEncC では `--preset` と異なる引数になっていました（省略形はどちらも `-u` で共通）。
exe 内のヘルプには同じ機能のオプションとして `-u, --quality` と記述されていたので、VCEEncC_Options.ja.md の誤植、あるいは実装上のミスかなーと思っています。取り急ぎご報告まで。

**Comment by rigaya** [comment]
ご報告ありがとうございます。

> exe 内のヘルプには同じ機能のオプションとして -u, --quality と記述されていたので、VCEEncC_Options.ja.md の誤植、あるいは実装上のミスかなーと思っています。

おっしゃる通り、VCEEncC_Options.ja.md と実装が一致していませんでした。QSVEnc/NVEncと統一されてないのはよろしくないので、今後NVEncC に合わせていこうと思います。

**Comment by tsukumijima** [comment]
了解です！対応ありがとうございました！
