### ISSUE TITLE
AMD Virtual Super Resolution

### ISSUE THREAD

**Issue by quamt** [rigaya/VCEEnc#22]
I saw that for NVENC there is the super resize filer.

Would this be possible for Radeon cards too? 
As AMD provides Virtual Super Resolution and it seems to be similar.

`https://www.amd.com/en/support/kb/faq/dh-010`
`https://www.amd.com/en/technologies/vsr`

Thank you

**Comment by rigaya** [comment]
I'm sorry, but currently I have no plan for this.
