### ISSUE TITLE
Contrast Adaptive Sharpening (CAS) 

### ISSUE THREAD

**Issue by quamt** [rigaya/VCEEnc#23]
Hello,

Is it possible to include CAS on GPU enhancement?

As far as I understand it should not be limited to AMD engines only, but could be also applied by Nvidia cards.

`https://gpuopen.com/fidelityfx-cas/`
`https://github.com/GPUOpen-Effects/FidelityFX-CAS/tree/master/CasCmdLine`

Thank you.

**Comment by rigaya** [comment]
I'm sorry, but currently I have no plan for this.
