### ISSUE TITLE
VCEEnc encodes x265 at double the input framerate

### ISSUE THREAD

**Issue by AbstractTheorem** [rigaya/VCEEnc#3]
Issue is mentioned here (StaxRip):

https://github.com/stax76/staxrip/issues/280

I have tried it using all possible decoding inputs and the lines from StaxRip which are being fed to VCEEnc seem to be correct so it was suggested this may be an issue with VCEEnc.

**Comment by stax76** [comment]
jocer71 says it's fixed in the latest driver.

https://github.com/stax76/staxrip/issues/280#issuecomment-331459685

**Comment by rigaya** [comment]
Thanks for letting me know.
