### ISSUE TITLE
HEVC 10-bit encoding produces bad video file

### ISSUE THREAD

**Issue by cdgriffith** [rigaya/VCEEnc#31]
If you encode a 8-bit movie with output-depth set to 10, it will cause errors while decoding. 

For example: 

```
VCEEncC64.EXE -i video.mp4 -c hevc --vbr 5000  --output-depth 10 -o video-10.mkv
```

Will produce a file that has different issues across different players. 

VLC will oversaturate the results: 
![vlc](https://user-images.githubusercontent.com/3275435/128960358-5068183f-dedc-4ab6-9428-fe2c2468b860.PNG)

Whereas windows media player will have extra bars off to the right side of it: 
![windows media player](https://user-images.githubusercontent.com/3275435/128960394-54605671-4c2a-4735-9d25-26c2741f5dba.PNG)

Setting a 8-bit movie to `output-depth 8` works as expected, and a 10-bit video to `output-depth 10` also works.  This is not a major issue for me. Just something that other encoders seem to handle fine and wasn't sure if it was an error or as intended.

**Comment by rigaya** [comment]
Thank you for reporting the issue.

It seems like the encoder has been setting unexpected colormatrix, colorprim when output depth is 10bit, when the input is 8bit. [VCEEnc 6.14](https://github.com/rigaya/VCEEnc/releases/tag/6.14) will override these metadata after encoding to avoid this issue.

**Comment by cdgriffith** [comment]
Tested and working as expected, thanks!
