### ISSUE TITLE
[Feature Request] Add Quality Variable Bit Rate for HEVC (or raise error)

### ISSUE THREAD

**Issue by cdgriffith** [rigaya/VCEEnc#32]
New feature in AMF 1.4.21 https://github.com/GPUOpen-LibrariesAndSDKs/AMF/releases/tag/v.1.4.21

**Comment by cdgriffith** [comment]
I'm an idiot and wasn't looking at your newest release, you already got it!

**Comment by cdgriffith** [comment]
Actually, reopening with a twist, I tried this with HEVC but it just fell back into CQP mode? 

Looks like it's not set up yet https://github.com/rigaya/VCEEnc/blob/7b8a2d4803a49b3387d91f6a3335c0f02d70c9c1/VCECore/vce_param.h#L307  that or it's not supported, in which case I would except and error to be raised instead of silently falling back to a different type of encode.

**Comment by rigaya** [comment]
[VCEEnc 6.15](https://github.com/rigaya/VCEEnc/releases/tag/6.15) will show error message when using QVBR with HEVC encoding as below.
```QVBR unsupported for HEVC encoding!```
