### ISSUE TITLE
Rotate and flip combined do not act as expected

### ISSUE THREAD

**Issue by cdgriffith** [rigaya/VCEEnc#35]
Consider the following test image: 

![point](https://user-images.githubusercontent.com/3275435/131927645-5a6f0773-82f9-4c37-876b-fb47e8c7b7b9.jpg)

If you were to flip it 90 degrees: 

![point 90](https://user-images.githubusercontent.com/3275435/131927655-4ec72853-3d2a-4e9f-9db6-b0c777a10107.jpg)

And then apply a horizontal flip, I get this expected image:

![point 90 flip](https://user-images.githubusercontent.com/3275435/131927658-5146fb34-e0e6-4bb9-8199-ac710a50ffcb.jpg)

However, if I use the command:

```
--vpp-rotate 90 --vpp-transform flip_x=true,flip_y=false

```

It instead looks like: 

![point wrong](https://user-images.githubusercontent.com/3275435/131927674-b8e26fec-407c-404a-9f7a-31b6b9920a2a.png)

Using the same transform with FFmpeg (`-vf transpose=1,hflip`) it does apply correctly.  Test video to play with: 
[point.zip](https://github.com/rigaya/VCEEnc/files/7102278/point.zip)

**Comment by rigaya** [comment]
--vpp-rotate and --vpp-transform cannot be used together in current implementation, and it can be used only once.

However, you can use "--vpp-transform transpose=true" to get what you expect.

**Comment by cdgriffith** [comment]
Sorry for late follow up, but thank you for the info and knowing that limitation!
