### ISSUE TITLE
VCEENC crash with dedicated gpu --check-features command

### ISSUE THREAD

**Issue by LuisB79** [rigaya/VCEEnc#37]
I have 2 radeon graphics cards, an integrated Radeon based on navi, and an RX6800m

when i tried to encode something it crashed into a black screen, and if i type the --check-features command this appears

0x00007FF766DC4F3B (0x00007FF766F73F20 0x000000E4B68FEAD9 0x000000E4B68FEBC8 0x0000000000000001)
0x00007FF766E6F4F2 (0x000000E4B68FECC0 0x0000025F33AD85F0 0x0000025F33AD85F0 0x0000000000000001), clrngMrg31k3pDeviceRandomU01Array_() + 0xB13E bytes(s)
0x00007FF766DE26B8 (0x0000000000000001 0x000000E4B68FECF0 0x0000000000000000 0x0000000000000000)
0x00007FF766DC3052 (0x000000180000000E 0x0000000000000001 0x0000000000000000 0x00007FF766F64B8C)
0x00007FF766DC3539 (0x0000000000000002 0x0000025F33AE4440 0x0000000000000001 0x000000003C00003C)
0x00007FF766DC43F7 (0x0000000000000000 0x0000000000000000 0x0000025F33AE4440 0x0000000000000000)
0x00007FF766F02E40 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), clrngGetLibraryDeviceIncludes() + 0x8080 bytes(s)
0x00007FFEE59454E0 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x10 bytes(s)
0x00007FFEE724485B (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x2B bytes(s)

i'm using Windows 11 21H2
Rx6800m driver Driver Version
21.30.37.01-211116a-373733E-RadeonSoftware

**Comment by rigaya** [comment]
Thank you for reporting, shall be fixed in [VCEEnc 6.17](https://github.com/rigaya/VCEEnc/releases/tag/6.17).
