### ISSUE TITLE
VCEEnc do not actually apply --ref parameter, it always =1 in resulting file

### ISSUE THREAD

**Issue by vasyl-zabolotniy** [rigaya/VCEEnc#38]
Despite proper stats in the console (same as in encoding parameters), actual number of reference frames is always =1 according to Mediainfo (and other analyzer too).
Tested and confirmed on v6.13, v6.16
Platform - Ryzen5 2400g, Win10 x64, driver v21.10.2-win10-win11-64bit-oct25

**Comment by rigaya** [comment]
RX460, Win11 x64, driver 21.12.1 seems to have no problem in H.264 encoding. I've tested --ref 2 and --ref 4, MediaInfo has also shown the value set.

There might be some hardware or driver limitation, resulting fixed 1 ref frames.

**Comment by vasyl-zabolotniy** [comment]
The weird thing is that I can actually get up to 3 refs in the output file by adding --ltr 2 parameter... but the value of --ref is ignored nonetheless. Seems it's locked to 1 permanently..
