### ISSUE TITLE
clRNG missing

### ISSUE THREAD

**Issue by markg85** [rigaya/VCEEnc#40]
Hi,

I know, the library can be downloaded from [here](https://github.com/clMathLibraries/clRNG).
Still, the library is ~7 years old and seems dead from a maintenance point of view.

This is making the compilation of VCEEnc a little more complicated...

Would it be possible to add a flag to the compilation to optionally disable OpenCL functionality?
Ideally one would use this library for the hardware encoding side anyhow. What in the codebase even uses a RNG?

Best regards,
Mark

**Comment by rigaya** [comment]
clRNG is used in [--vpp-deband](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#--vpp-deband-param1value1param2value2) option, which requires random generator.
https://github.com/rigaya/VCEEnc/blob/master/VCECore/rgy_filter_deband.cpp

Unfortunately, I hesitate to add a flag to disable OpenCL filters on compile time. It will require too many ifdef macro blocks by the flag, which will make the source code complicated.

**Comment by markg85** [comment]
Hi @rigaya,

I did just manage to compile VCEEnc.
In your code you rely on the library folder in clRNG and the sourcecode ofthe function (the .c file). Neither exist in the released version of clRNG.
Not a big issue, just took me some minutes to figure out i was missing files.

Is it perhaps possible to change to a library that is more widely known and used that offers the same functionality?
Or perhaps to make VCEEnc buildable using the released version of clRNG as opposed to a source clone?

**Comment by rigaya** [comment]
As you might know, the clRNG revision used (the latest revision) is added as submodule in VCEEnc repository and the path is already set in VS project file.

The submodules (including clRNG) will be downloaded for you by using git command with ```--recursive``` option, which should simplify the build (as written in [Build.en.md](https://github.com/rigaya/VCEEnc/blob/master/Build.en.md))
```
git clone https://github.com/rigaya/VCEEnc --recursive
```

Alternative libraries can be found, RandomCL seems to be easier in terms of build, but I think clRNG is enough...
- [RandomCL](https://github.com/bstatcomp/RandomCL)
- [rocRAND](https://github.com/ROCmSoftwarePlatform/rocRAND)

**Comment by markg85** [comment]
> As you might know, the clRNG revision used (the latest revision) is added as submodule in VCEEnc repository and the path is already set in VS project file.

I downloaded your source build from the releases. That might have been stupid on my part ;) but it doesn't have those sources.

**Comment by rigaya** [comment]
Yes, unfortunately downloads from github releases does not include submodules (such as clRNG), I think that is the default for github releases.

I might better change the position of the link to the build instruction ([Build.en.md](https://github.com/rigaya/VCEEnc/blob/master/Build.en.md)) to the more upper part of Readme, which is now on the bottom.
