### ISSUE TITLE
Make output pipe'able

### ISSUE THREAD

**Issue by markg85** [rigaya/VCEEnc#41]
Hi,

This tool accepts input from stdin that for examples comes from ffmpeg.
I'd like to do the exact opposite. Pipe the output of this tool to ffmpeg!

If the output from VCEEncC could be piped back into ffmpeg then it becomes possible to use ffmpeg for further processing. For example, more filters could be applied to the output date. Or it can be passed to `-f mpegts udp://127.0.0.1:2222` for live broadcasting purposes.

Another reason why i'd like to have this feature is because AMD AMF is just barely working in ffmpeg. Enough to get something useful, but too little to use the fancy AMF features. VCEEncC is miles ahead in that regard and basically exposes all the AMD features in a command line utility. That's awesome!

I hope you could consider this!

Best regards,
Mark

**Comment by rigaya** [comment]
I'm not exactly sure about your usage, but VCEEncC is able to write to pipe(stdout) in simple use cases.

For example, it is able to pass output to ffmpeg by pipe like below.

VCEEncC64.exe -i sample_movie_2.mp4 --audio-copy --output-format mpegts -o - | ffmpeg.exe -y -i - -c:v copy -c:a copy output.mp4

**Comment by markg85** [comment]
Hi @rigaya,

That's great! I think i missed that option in the documentation. Thank you for clarifying!
The purpose i had for it was streaming. Which in ffmpeg would be: `ffmpeg -i video.mp4 -f mpegts udp://127.0.0.1:2222` so i suppose in your example i could just do: `VCEEncC64.exe -i video.mp4 --audio-copy --output-format mpegts -o - | ffmpeg.exe -y -i - -c:v copy -c:a copy -f mpegts udp://127.0.0.1:2222`

Thank you!
Closing this issue.
