### ISSUE TITLE
Typo in Instructions for Windows?

### ISSUE THREAD

**Issue by wbedard** [rigaya/VCEEnc#43]
Given the description of this project and the fact that AMD provides official drivers for Windows, I have to believe that there is a typo in the installation instructions for Windows where it indicates to ["Install Intel Graphics driver."](https://github.com/rigaya/VCEEnc/blob/master/Install.en.md#1-install-intel-graphics-driver)

**Comment by rigaya** [comment]
Thank you for pointing out the typo, now it is fixed to "Install AMD Radeon Driver."
