### ISSUE TITLE
Subtitles automatically being given 'Default' disposition

### ISSUE THREAD

**Issue by cdgriffith** [rigaya/VCEEnc#44]
I want to set subtitles to `none` for disposition but don't see any way to do that via the docs. 

If I give only `sub-copy` and language (` --sub-copy 1 --sub-metadata  1?language='eng'`), it goes ahead and sets that track as `default` even though it shouldn't have a disposition. 

I looked at `sub-disposition` but it doesn't list a `none` option like ffmpeg does. https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#--audio-disposition-intorstringstringstring 

Full example command: 

```
".\VCEEncC64.exe" --avhw -i "video.mkv" --video-metadata clear  --chapter-copy -c hevc --vbr 10000 --qp-max 26 --preset slow --tier high --colormatrix bt2020nc --transfer smpte2084 --colorprim bt2020 --output-depth 10 --motion-est q-pel --chromaloc auto --colorrange auto --avsync cfr  --audio-metadata 1?language=eng --audio-stream 1?:stereo --audio-codec 1?aac --audio-bitrate 1?128  --audio-metadata 1?clear --audio-metadata 1?title="Stereo" --audio-metadata 1?handler="Stereo"   --sub-copy 1 --sub-metadata  1?language='eng' -o "output.mkv"
```

Anyway to remove disposition? 

Thanks!

**Comment by rigaya** [comment]
Removing disposition can be done by following option.
```
--sub-disposition 1?unset
```
However, the muxer will automatically add "default" to the first subtitle track by default. To disable this, you will need ```-m default_mode:infer_no_subs```. (Please check example of [-m (--mux-option)](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#-m---mux-option-string1string2).)

Therefore, I think option below should work.
```
--sub-copy 1 --sub-disposition 1?unset -m default_mode:infer_no_subs
```

**Comment by cdgriffith** [comment]
That does the trick, thank you so much rigaya, you're awesome!
