### ISSUE TITLE
Inconsisted results of --vpp-mpdecimate. Each consequential run shows different output

### ISSUE THREAD

**Issue by vasyl-zabolotniy** [rigaya/VCEEnc#45]
It's like a randomized output - wide range and no visible pattern.
test file: https://drive.google.com/file/d/1YzkSO-BbqF4Qk9lSZW5ZfogV8QyWAi9O/view?usp=sharing
example of filter settings: --vpp-mpdecimate hi=1520,lo=760,frac=0.1,log=true

**Comment by rigaya** [comment]
Thank you for letting me know the issue, it looks like something weird was happening when sending the calculation result from GPU side to CPU side. I have improved stability in [VCEEnc 7.00](https://github.com/rigaya/VCEEnc/releases/tag/7.00), which should give same result per run.

**Comment by rigaya** [comment]
I'll close this issue as the problem should have been fixed.
