### ISSUE TITLE
AVC B-frames not working with RDNA2 (New AMF Feature)

### ISSUE THREAD

**Issue by cdgriffith** [rigaya/VCEEnc#46]
As of last weeks releases of AMF looks like we should finally have B-frame support https://github.com/GPUOpen-LibrariesAndSDKs/AMF/releases/tag/v1.4.24

Using the check-hardware feature also see that it's enabled

```
.\VCEEncC64.exe --check-features
device #0: AMD Radeon RX 6900 XT
H.264/AVC encode features
10bit depth:     no
acceleration:    Hardware-accelerated
max profile:     High
max level:       High
max bitrate:     2147483 kbps
ref frames:      1-16
Bframe support:  yes
HW instances:    2
max streams:     16
timeout support: yes
```

Using an encode with `--bframes 2`  I do see the line: 

```
Bframes:       2 frames, b-pyramid: off
```

However when analysing the resulting file using ffprobe (`ffprobe.exe -show_frames -select_streams v:0 -show_entries frame=pict_type output.mkv` ) it only has I and P frames still. 

I imagine this may just require an upgrade to AMF 1.4.24 internally, but wanted to bring it to your attention. Thank you!

**Comment by rigaya** [comment]
I have updated AMF to 1.4.24 in [VCEEnc 7.00](https://github.com/rigaya/VCEEnc/releases/tag/7.00), which might solve this issue. (Please note I haven't tested myself as I don't have RX6xxx series myself).

**Comment by cdgriffith** [comment]
Thank you so much, seems to be working as expected after the update!

```
[FRAME]
pict_type=I
[/FRAME]
[FRAME]
pict_type=B
[/FRAME]
[FRAME]
pict_type=B
[/FRAME]
[FRAME]
pict_type=B
[/FRAME]
[FRAME]
pict_type=P
[/FRAME]
[FRAME]
pict_type=B
[/FRAME]
[FRAME]
pict_type=B
[/FRAME]
[FRAME]
pict_type=B
[/FRAME]
```

**Comment by rigaya** [comment]
Thank you for confirming this works fine.
