### ISSUE TITLE
More filters

### ISSUE THREAD

**Issue by LuisB79** [rigaya/VCEEnc#49]
Is it possible to have deblocking filters, or better temporal denoising filters such as nlmeans based, bm3d or bm4d, wnnm, fourier based denosing filters, or to have better debanding filters?.

**Comment by LuisB79** [comment]
Will this be taken into consideration?, if not, to close the issue.

**Comment by rigaya** [comment]
There are already many denoise filters supported, and deband is supported by vpp-deband.

For 3d denoise filters, it can be possible for me to copy --vpp-convolution3d implementation from NVEnc/QSVEnc.

**Comment by LuisB79** [comment]
> There are already many denoise filters supported, and deband is supported by vpp-deband.
> 
> For 3d denoise filters, it can be possible for me to copy --vpp-convolution3d implementation from NVEnc/QSVEnc.

what about deblocking filters?, and could you provide better documentation on the denoising filters?

**Comment by rigaya** [comment]
You can go through for [vpp-options](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#vpp-options) for the documentation of filters.

**Comment by LuisB79** [comment]
> You can go through for [vpp-options](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#vpp-options) for the documentation of filters.

ok, what about debolcking filters?

**Comment by LuisB79** [comment]
> You can go through for [vpp-options](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#vpp-options) for the documentation of filters.

do you have a paper, or somewhere where i could check the quality of knn, pmd and convoluton 3d based denoisers?, where did you get them from?, what does "3d noise reduction" even means?

**Comment by rigaya** [comment]
I don't have any papers, please note that this is **not** a research of noise reduction algorithms. You can simply just test filters yourself, as the binaries are already released, and the parameters are documented.

**Comment by rigaya** [comment]
Current plan is to add --vpp-concolution3d in the near future.

There is no plan to add other filters in the near future.

**Comment by LuisB79** [comment]
> Current plan is to add --vpp-concolution3d in the near future.
> 
> There is no plan to add other filters in the near future.

but the release 7.0 has already convolution3d i'm confused, as to per my last request of the quality of the current denoiser filters, will you give more data?
