### ISSUE TITLE
storage->SetProperty(HevcEnablePreAnalysis)=false failed: invalid param

### ISSUE THREAD

**Issue by Morpheus1123** [rigaya/VCEEnc#5]
Hello. These are my hardwares and softwares.
CPU:AMD Ryzen7 3800X
GPU:AMD Radeon RX Vega 64
GPU driver:20.2.1
OS:Windows10 1909
VceEnc:5.03

This is issue.
`J:\Program Files\VCEEncC503>VCEEncC64 --codec hevc --vbr 6000 -i "G:\Index\test\test1.mp4" -o "G:\Index\test\test1out.mp4"`

Then VceEnc says:
--------------------------------------------------------------------------------
**storage->SetProperty(HevcEnablePreAnalysis)=false failed: invalid param..**
VCEEnc (x64) 5.03 (r451) by rigaya, Feb 29 2020 10:07:55 (VC 1924/Win/avx2)
OS Version     Windows 10 x64 (18363)
CPU:           AMD Ryzen 7 3800X 8-Core Processor (8C/16T)
GPU:           Radeon RX Vega, AMF Runtime 1.4.16 / SDK 1.4.16
Input Info:    avvce: H.264/AVC, 1920x1080, 30/1 fps
Vpp Filters    copyDtoD
Output:        H.265/HEVC  main @ Level 4 (main tier)
               1920x1080p 0:0 30.000fps (30/1fps)
               avwriter: hevc => mp4
Quality:       balanced
VBR:           6000 kbps, Max 12000 kbps
QP:            Min: 0, Max: 51
VBV Bufsize:   12000 kbps
Bframes:       0 frames
Pre Analysis:  off
Ref frames:    2 frames
LTR frames:    0 frames
Motion Est:    Q-pel
Slices:        1
GOP Len:       300 frames
Others:        deblock hrd

encoded 4266 frames, 166.20 fps, 6000.96 kbps, 101.73 MB
encode time 0:00:25, CPU: 0.1%, VE: 99.4%, VD: 99.4%
frame type IDR   15
frame type I     15,  total size   2.36 MB
frame type P   4251,  total size  99.37 MB

If I add "--pa",VceEnc says:
storage->SetProperty(HevcEnablePreAnalysis)=true failed: invalid param..
storage->SetProperty(PAActivityType)=0 failed: invalid param..
storage->SetProperty(PACAQStrength)=1 failed: invalid param..
storage->SetProperty(PAMaxQPBeforeForceSkip)=35 failed: invalid param..
storage->SetProperty(PASceneChangeDetectionEnable)=true failed: invalid param..
storage->SetProperty(PASceneChangeDetectionSensitivity)=1 failed: invalid param..
storage->SetProperty(PAStaticSceneDetectionEnable)=true failed: invalid param..
storage->SetProperty(PAStaticSceneDetectionSensitivity)=2 failed: invalid param..

This issue does not occur on 5.01.

**Comment by rigaya** [comment]
VCEEnc 5.02 uses the new pre analysis feature in [AMF](https://github.com/GPUOpen-LibrariesAndSDKs/AMF) 1.4.16.

_Version 1.4.16: AMD Radeon Software Adrenalin Edition 20.2.1 or newer. Added the Pre-Analysis component to improve perceptual quality of encoded video._

I'm afraid the new pre analysis feature is not supported on  Radeon RX Vega, as [AMF_Video_PreAnalysis_API.pdf](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/tree/master/amf/doc) states that

_The AMF PA feature is supported by Radeon RX 5000 Series or newer GPUs as well as Ryzen 2000 U/H series or newer APUs._

**Comment by Morpheus1123** [comment]
Thanks for your answer!

**Comment by quamt** [comment]
Apologise for reopening this thread.
Is there any way to have both versions available?

I mean after 5.01 till 6.00 there been a lot of fixes and improvements implemented which version 5.01 doesn't have.
Is it possible to support previous hardware in 6.00 with preanalysis again?
Or will there be issues in regards of compatibility with AMF version?
