### ISSUE TITLE
Will there be an English version of VCEEnc?

### ISSUE THREAD

**Issue by Begemotoid** [rigaya/VCEEnc#53]
Now I use VCEEnc 7.0 in AviUtl. The Video Encoding settings are not fully translated into English, some settings are written in Japanese. And unfortunately, many people do not know Japanese.

**Comment by rigaya** [comment]
I'm sorry but I must say it will not be in near future.

The Aviutl output plugins I've made lacks multi language support, therefore it is Japanese only now. (VCEEncC is English only.)

I've already done English translation in other Aviutl plugin [x264guiEx](https://github.com/rigaya/x264guiEx), but required too much time for me. Adding multi language support implementation and creating large [English table](https://github.com/rigaya/x264guiEx/blob/master/x264guiEx/x264guiEx.en.lng) was actually lot of work, and the same work will be needed for VCEEnc and other output plugins to add English translation.

Also, my priority for English translation is x265guiEx, ffmpegOut, NVEnc, QSVEnc, svtAV1guiEx and then VCEEnc.

**Comment by Begemotoid** [comment]
Thanks for the answer. Can you add to the description that VCEEnc encoding can be used in the Fastflix application? It has a pretty good implementation of VCEEnc.

**Comment by Begemotoid** [comment]
I will also say that VCEEnc is used in the StaxRip application. Perhaps this is the best application to use VCEEnc.

**Comment by rigaya** [comment]
Yes, I know VCEEnc can be used from Staxrip, Hybrid and Fastflix, but I'll not add descriptions about the GUI apps.

**Comment by rigaya** [comment]
It took some time, but [VCEEnc 7.11](https://github.com/rigaya/VCEEnc/releases/tag/7.11) has English translation for the Aviutl plugin.
