### ISSUE TITLE
rigaya - What options do you recommend for optimal encodes?

### ISSUE THREAD

**Issue by GlitterKill** [rigaya/VCEEnc#55]
VCEEnc is quite different from other encoders so info about the options (documentation) is hard to find.  At default settings the lower quality of 265 encodes are very noticeable when compared with x265 software encodes.  Plus, the file sizes are larger.  At least that has been my experience so far.  Do you have some recommended settings to improve encode quality and/or lower file sizes for good quality encodes?  For example, implementing the unsharp filter seems to help quite a bit with quality.

Thanks for the great work you are doing!

**Comment by rigaya** [comment]
> Do you have some recommended settings

There is no recommendation from me.

VCEEnc exposes many of the parameters that AMF SDK provides, and enables users to change them by options to find the suitable options they want. All options are written [here](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md) so please have a look. (I think [html help](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md) shall be better than console help to look.)

Basically, you can follow steps below
1. select [codecs](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#-c---codec-string)(H.264/HEVC)
1. test encode modes ([CQP](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#--cqp-int-or-intintint)/[VBR](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#--vbr-int)/[QVBR](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#--qvbr-int-h264-only)/[CBR](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#--cbr-int))
1. change [preset](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#-u---preset)
1. then test the [other options](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#other-options-for-encoder) (bframes, vbqa and so on).

There are also simple [filters](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#vpp-options) provided in VCEEnc. They are only simple filters which can be processed fast enough that hw encoder can take advantage, so if you need more complex and high quality filters, it is recommended to use Avisynth/VapourSynth filters instead.

But as far as I tested on RX460/RX5500XT, VCE/VCN quality is lower compared to x264/x265 software encoders, and also results a bit lower quality compared to Intel QSV/NVIDIA NVENC. (Of course, things might have changed with RX6xxx)

**Comment by rigaya** [comment]
I'll close this issue, as the topic has been answered.
