### ISSUE TITLE
How does VBAQ work?

### ISSUE THREAD

**Issue by Begemotoid** [rigaya/VCEEnc#57]
Please explain what enabling VBAQ mode does. What encoding modes (CQP, VBR, CBR) are suitable for this? I can't figure out the effect of turning this setting on and off. In general, adaptive quantization is considered the principle of operation of the CRF.

**Comment by rigaya** [comment]
VBAQ should work with VBR and CBR but not with CQP mode.

The explanation of VBAQ from AMF document (AMF_Video_Encode_API.pdf) is below.

> Enables/disables VBAQ VBAQ stands for “Variance  Based Adaptive  Quantization”. The basic idea of VBAQ: Human visual system is  typically less sensitive to  artifacts in highly textured  area. In VBAQ mode, we use  pixel variance to indicate the  complexity of spatial texture.  This allows us to allocate  more bits to smoother areas.  Enabling such feature leads to  improvements in subjective  visual quality with some  content.

**Comment by rigaya** [comment]
VBAQ will work with HEVC also. ([AMF_Video_Encode_HEVC_API.pdf](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/053040d662b4d88d9994dc706b948ee409292537/amf/doc/AMF_Video_Encode_HEVC_API.pdf))
