### ISSUE TITLE
How to use B-frames?

### ISSUE THREAD

**Issue by Galaxoid-333** [rigaya/VCEEnc#58]
In this article I read about the use of B frames:
https://codecalamity.com/amd-re-introduces-the-b-frame/

But when I use these B frame settings there is no effect. I use CQP/VBR/CBR, 264 and 265 codecs. Version VCEEnc 7.00.

Can you tell me how to use B frames?

**Comment by rigaya** [comment]
I cannot have bframes enabled on RX5500XT.
```Bframes is not supported on this device, disabled.```

Therefore, I think we need RX6xxx series for H.264 bframes, as the articles uses RX6900.

**Comment by cdgriffith** [comment]
Correct, only latest RDNA2 has re-enabled B-frames, sorry I wasn't clearer in the article about which versions support it. AMD doesn't prove a nice list like Nvidia does with their support Matrix for NVENC, so I honestly don't know which do or don't have it. 

Have to manually check with `VCEEncC64.exe --check-features`  and see if it lists `Bframe support:  yes` 

If it does support it just need to add `--bframes 3` (and I also recommend `--b-pyramid`) to your encoding command.

**Comment by GabeBlincoln** [comment]
One oddity is that if --bframes is specified when the codec is HEVC,  VCEEnc will warn that it isn't supported (6900XT, this is apparently correct), but doesn't complain about --b-pyramid.

**Comment by rigaya** [comment]
B-frame support check is for --bframes only, --b-pyramid is just ignored.

I'll close this issue as the topic has been answered.
