### ISSUE TITLE
[Feature Request] HDR10+ possible?

### ISSUE THREAD

**Issue by cdgriffith** [rigaya/VCEEnc#59]
Hi rigaya, is it possible to add HDR10+ to this encoder like the nvenc and qsv one have? 

I don't know if you are able to do that at the muxing level or if the actual encoder needs to support that, so I totally understand if it's not possible.

**Comment by rigaya** [comment]
Unfortunately, it is not possible to handle HDR10+ in VCEEnc as the same way as NVEnc/QSVEnc.

The feature is implemented using the encode API feature to add metadata each frame, supported by NVENC SDK and Intel MediaSDK/oneVPL. Unfortunately I could not find this kind of feature in AMF SDK. I'll need to find a different way, but would take some time.

**Comment by nyanmisaka** [comment]
AFAIK AMF supports this by passing [`AMFHDRMetadata`](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/5c78f194a396938ff0e72128712252151238e372/amf/public/include/components/ColorSpace.h#L108) struct to the [encoder](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/5c78f194a396938ff0e72128712252151238e372/amf/public/include/components/VideoEncoderHEVC.h#L214). It works for me in my ffmpeg patch.

https://patchwork.ffmpeg.org/project/ffmpeg/patch/20220706042314.1099-3-ovchinnikov.dmitrii@gmail.com/

**Comment by rigaya** [comment]
I'm afraid what is supported by AMFHDRMetadata and AV_FRAME_DATA_MASTERING_DISPLAY_METADATA, AV_FRAME_DATA_CONTENT_LIGHT_LEVEL is **static** HDR metadata.

For HDR10+(**dynamic** HDRPlus metadata), I think we'll need to handle AV_FRAME_DATA_DYNAMIC_HDR_PLUS (and [AVDynamicHDRPlus](https://github.com/FFmpeg/FFmpeg/blob/master/libavutil/hdr_dynamic_metadata.h#L323)) in libavutil/libavcodec, but I could not find corresponding structure supported in AMF SDK.

**Comment by rigaya** [comment]
[VCEEnc 7.12](https://github.com/rigaya/VCEEnc/releases/tag/7.12) adds support for dynamic HDRPlus metadata (--dhdr10-info) by implementing it in a different way compared to previous QSV/NVENC implementation.

**Comment by cdgriffith** [comment]
You're awesome! ❤️
