### ISSUE TITLE
how use --vpp-afs to deinterlace movie 29.97-->59.94

### ISSUE THREAD

**Issue by feijiaa1** [rigaya/VCEEnc#6]
how use --vpp-afs to deinterlace movie 29.97-->59.94
I can't find setting，it only output 29.97。
but QSVENC has setting --vpp-deinterlace bob can 29.97-->59.94，i can't found similar setting in VCEENC。

**Comment by rigaya** [comment]
--vpp-afs unfortunately does not have a mode for 29.97 -> 59.94p conversion.

**Comment by rigaya** [comment]
I7ll close this issue as the question has bee answered.
