### ISSUE TITLE
RX 6700 XT and AMF Runtime 1.4.26 / SDK 1.4.26 issues

### ISSUE THREAD

**Issue by quamt** [rigaya/VCEEnc#65]
Hello when using the AMF Runtime 1.4.26 / SDK 1.4.26 and RX 6700 XT together with VCEEnc (x64) 7.11 (r1236) there are some strange issues and behaviours.

1. When selecting bframes there is always an error message but these has not been set:
```
storage->SetProperty(BPicturesDeltaQP)=6 failed: invalid param..
storage->SetProperty(ReferenceBPicturesDeltaQP)=4 failed: invalid param..
```
2. When converting AVC to AVC usage of bframes crashes the decoder

3. Usage of --pa lets the decoder crash too

Attached debug logs

[6070-bframes.txt](https://github.com/rigaya/VCEEnc/files/9731586/6070-bframes.txt)

[6070-pa.txt](https://github.com/rigaya/VCEEnc/files/9731589/6070-pa.txt)

**Comment by quamt** [comment]
After further investigation it seems to be that the error is related to the source files.
Meaning, depending on the source file the AMD decoder is "choking" on the file when certain options are enabled.
I also noticed after lots of investigation that lookahead causes "choking" when --avhw is used. 
Using --avsw and lookahead is not causing any trouble.

One very strange part is that the CPU/GPU usage is very low when using either --avsw or --avhw, at least that what the task manager shows.

**Comment by rigaya** [comment]
> 1. BPicturesDeltaQP, ReferenceBPicturesDeltaQP

It seems like they are not currently supported yet.

> decoder/PA crush

I also have pre-analysis sometimes crushing, but cannot find the reason or condition which causes the error, because it sometimes works fine and sometimes don't. The debugger shows crush in the amf runtime module, which makes hard to debug.

I might need to check further.

**Comment by rigaya** [comment]
> decoder/PA crush

This should have been fixed in VCEEnc 8.00, which improves stability when using pre analysis.

**Comment by quamt** [comment]
Ok. Thank you.
I will check and feedback.

**Comment by quamt** [comment]
Look fine.
Thank you.
