### ISSUE TITLE
How to incorporate latest VCEEnc options in StaxRip?

### ISSUE THREAD

**Issue by GlitterKill** [rigaya/VCEEnc#66]
How can I add my own encoding profile with edited options that are related to this latest version?  For example, changing the Basic, Mode options in the AMD H264 menus to include ones not currently there (in bold below).

--cbr <int>
**--cbrhq <int> [H.264 only]**
--vbr <int>
**--vbrhq <int> [H.264 only]**
--qvbr <int> [H.264 only]

**Comment by rigaya** [comment]
Unfortunately, I cannot answer about usage of StaxRip.

**Comment by Begemotoid** [comment]
In Staxrip, it is possible to manually add the necessary parameters. And you should have the latest version of VCEEnc downloaded in the program directory. But the functionality is still not guaranteed. And as far as I know the Staxrip developer doesn't support it anymore.
