### ISSUE TITLE
AMD VCE doesn't apply FPS change (StaxR 2.13.0) !

### ISSUE THREAD

**Issue by metagondria** [rigaya/VCEEnc#67]
Hello,

Iam searching for an away to convert old dvd content using my RX6600 gpu (VCE).
VCe in staxrip works awesome (very fast xxx fps), as long i don't change pal fps to film fps !!

When i use changeFps to 24 , staxrip output preview will tell me 24fps... But actuall output file is still 25fps !!!

Not matter which frameserver i use (LwlibavSource , D2Vsource), the output file has always 25fps !!!  
Only Cpu methode encode applies the right fps (avisynth/vapour)!!!

Also, using other filters like "selectEvery(), doesn't apply 25fps → 24fps neither !

I hope there's some sollution to convert pal 25fps to 24fps using amd VCE...

much obliged,

cheers,

**Comment by DimkaTsv** [comment]
Answered here:
https://github.com/rigaya/VCEEnc/issues/89
