### ISSUE TITLE
Deinterlace issue, --vpp-afs do not work on RX 5700 series

### ISSUE THREAD

**Issue by Begnion** [rigaya/VCEEnc#7]
When using --vpp-afs on RX 5700,
`VCEEncC64 --interlace bff --vpp-afs preset=anime -i "C:\xxx.mp4" -c avc -u slow -o "C:\xxx.mp4"`

it will get back some errors

>`build log of gfx1010...
C:\Users\mxxx\AppData\Local\Temp\comgr-e903f2\input\CompileCLSource:252:19: error: non-kernel function variable cannot be declared in local address space
    __local float s_tmp[3][SHARED_C_Y][SYN_BLOCK_INT_X];
                  ^
C:\Users\mxxx\AppData\Local\Temp\comgr-e903f2\input\CompileCLSource:253:18: error: non-kernel function variable cannot be declared in local address space
    __local DATA s_out[SYN_BLOCK_Y][SYN_BLOCK_INT_X * 4];
                 ^
C:\Users\mxxx\AppData\Local\Temp\comgr-e903f2\input\CompileCLSource:650:1: warning: null character ignored
<U+0000>
^
C:\Users\mxxx\AppData\Local\Temp\comgr-e903f2\input\CompileCLSource:650:2: warning: null character ignored
<U+0000><U+0000>
        ^
C:\Users\mxxx\AppData\Local\Temp\comgr-e903f2\input\CompileCLSource:650:3: warning: null character ignored
<U+0000><U+0000><U+0000>
                ^
3 warnings and 2 errors generated.
Error: Failed to compile opencl source (from CL to LLVM IR).
Error (clBuildProgram): build program failure.
afs: failed to load VCE_FILTER_AFS_SYNTHESIZE_CL
Finished with error in VCEEncC.

But on RX 580, it can run correctly.

**Comment by rigaya** [comment]
I'm testing on R3 3200G without error, so it seems to be some problems related to Navi GPUs (which I don't have).

I'll check out what this error means...

> non-kernel function variable cannot be declared in local address space

**Comment by rigaya** [comment]
I have made some change to OpenCL code on [VCEEnc 6.01](https://github.com/rigaya/VCEEnc/releases/tag/6.01) trying to fix this issue, I hope it works, but I'm not sure as I don't have Navi GPUs.

**Comment by Begnion** [comment]
Now will get back some errors like this：

--------------------------------------------------------------------------
build log of gfx1010...
C:\Users\MASSPO~1\AppData\Local\Temp\comgr-e40878\input\CompileCLSource:651:1: warning: null character ignored
<U+0000><U+0000><EF>
^
C:\Users\MASSPO~1\AppData\Local\Temp\comgr-e40878\input\CompileCLSource:651:2: warning: null character ignored
<U+0000><U+0000><EF>
        ^
C:\Users\MASSPO~1\AppData\Local\Temp\comgr-e40878\input\CompileCLSource:651:3: error: source file is not valid UTF-8
<U+0000><U+0000><EF>
                ^
2 warnings and 1 error generated.
Error: Failed to compile opencl source (from CL to LLVM IR).

--------------------------------------------------------------------------
Error (clBuildProgram): build program failure.
afs: failed to load VCE_FILTER_AFS_SYNTHESIZE_CL
Finished with error in VCEEncC.

**Comment by rigaya** [comment]
Thanks for comfirming, probably 2nd error should be fixed in [VCEEnc 6.02](https://github.com/rigaya/VCEEnc/releases/tag/6.02).

**Comment by Begnion** [comment]
Now it can run correctly. Thanks !
