### ISSUE TITLE
CQP value no effect

### ISSUE THREAD

**Issue by philblue1** [rigaya/VCEEnc#70]
The CQP setting seems broken since 7.14 in AVC and HEVC, no noticeable change in bitrate.
Tested 7.12 & 7.13 working
7.14, 7.15 & 7.16 broken

```
AMD Lucienne 22.11.2
Windows 10 22H2
FastFlix 5.1.0
```

**Comment by rigaya** [comment]
Thank you for pointing out the issue, --cqp handling was wrong from VCEEnc 7.14 as you have mentioned.

Shall be fixed with [VCEEnc 7.17](https://github.com/rigaya/VCEEnc/releases/tag/7.17).

**Comment by philblue1** [comment]
Can confirm for AVC.
HEVC is unimpressed.

**Comment by rigaya** [comment]
Sorry, I forgot about HEVC, another fix for it has been made in [VCEEnc 7.18](https://github.com/rigaya/VCEEnc/releases/tag/7.18).
