### ISSUE TITLE
AVC/H.264 can't be seen on tv !

### ISSUE THREAD

**Issue by JOHNYBGOOD1** [rigaya/VCEEnc#71]
Hi.
I tried maybe 6, 7 versions of VCEEnc and with all converting from hevc to avc /h.264 for my old tv..well the tv can't see them !

My pc lenovo 15alc6, ryzen 5500U + iGPU Vega 7 (dx hw feature 12.1 and dx video hw feature 11.1) got it at promotion 299 euros, 15.6 inch, IPS screen 300 nits with 0 pulse modulation, meaning no flicker, 12 gb ddr4 3200mhz, 512 gb m.2 pci-e gen 3.0 + 1 tb hdd.
The problem might be my tv, and that is old tv LG made in 2013 with full screen **IPS** MATE non glare !
And i really care about this tv as i wouldn't change it (40 watt, 1080p, IPS & MATE screen, 80 cm).
From tv specs i got this
**_✎ We do not support any stream that contains GMC (Global Motion Compensation) or Qpel (Quarterpel Motion Estimation).
✎ Only H.264/AVC profile level 4.1 and lower is supported._**
Anyway i build the sources from amd git and even after removing qpel aka motion est still the same error the tv can't see them.
I did the same with VCEEnc sources and removed the above and again the same the tv can't see the files.

Funny i used over years QSVEnc for my N4200 + iGPU hd graphics 505 and all are working on my tv lg 2013.
But the performance of N4200 + iGPU 505 is about 19 fps for hevc and 44 fps for avc, where on ryzen 5500U + iGPU vega 7 i have over 80 fps for hevc and over 140 fps for avc.

Honestly i don't know what to do anymore, i modified so much and that even so my 2013 lg tv can't see files made by amd igpu.
Maybe amd is using a different profile for avc like latest ?

What ever i tried different programs too.. nothing made on vega 7 igpu can't be seen on the oldish 2013 tv lg.
Also on another LG tv 2017 all the files are playing normal.

Does anyone know a fix for this ?
I tried even ffmpeg and got the same thing, even encoding in cpu only the same thing..
I run out of options !

**Comment by JOHNYBGOOD1** [comment]
_**VCEEncC64.exe --check-features**_

device #0: AMD Radeon
H.264/AVC encode features
10bit depth:     no
acceleration:    Hardware-accelerated
max profile:     High
max level:       unknown
max bitrate:     2147483 kbps
ref frames:      1-16
Bframe support:  no
HW instances:    1
pre analysis:    yes
max streams:     16
timeout support: yes

H.264/AVC input:
Width:       128 - 4096
Height:      128 - 4096
alignment:   32
Interlace:   no
pix format:  NV12[1](native), YUV420P[7], YV12[2], BGRA[3], RGBA[5], ARGB[4]
memory type: DX11(native), OPENCL, OPENGL, HOST

H.264/AVC output:
Width:       128 - 4096
Height:      128 - 4096
alignment:   32
Interlace:   no
pix format:  NV12[1](native)
memory type: DX11(native), OPENCL, OPENGL, HOST

H.265/HEVC encode features
10bit depth:     yes
acceleration:    Hardware-accelerated
max profile:     main
max level:       unknown
max bitrate:     2147483 kbps
ref frames:      1-16
pre analysis:    yes
max streams:     16
timeout support: yes

H.265/HEVC input:
Width:       128 - 4096
Height:      128 - 4096
alignment:   32
Interlace:   no
pix format:  NV12[1](native), YUV420P[7], YV12[2], BGRA[3], RGBA[5], ARGB[4]
memory type: DX11(native), OPENCL, OPENGL, HOST

H.265/HEVC output:
Width:       128 - 4096
Height:      128 - 4096
alignment:   32
Interlace:   no
pix format:  NV12[1](native), P010[10](native)
memory type: DX11(native), OPENCL, OPENGL, HOST



device #0: AMD Radeon
H.264/AVC decode features
10bit depth:     no
acceleration:    Hardware-accelerated
max streams:     16

H.264/AVC output:
Width:       32 - 4096
Height:      32 - 2160
alignment:   32
Interlace:   yes
pix format:  NV12[1](native), BGRA[3], RGBA[5]
memory type: DX11(native)

H.265/HEVC decode features
10bit depth:     yes
acceleration:    Hardware-accelerated
max streams:     0

H.265/HEVC output:
Width:       32 - 7680
Height:      32 - 4320
alignment:   32
Interlace:   yes
pix format:  NV12[1](native), BGRA[3], RGBA[5]
memory type: DX11(native)

MPEG2 decode features
10bit depth:     no
acceleration:    Hardware-accelerated
max streams:     16

MPEG2 output:
Width:       32 - 1920
Height:      32 - 1080
alignment:   32
Interlace:   yes
pix format:  NV12[1](native), BGRA[3], RGBA[5]
memory type: DX11(native)

VP9 decode features
10bit depth:     yes
acceleration:    Hardware-accelerated
max streams:     16

VP9 output:
Width:       32 - 7680
Height:      32 - 4320
alignment:   32
Interlace:   yes
pix format:  NV12[1](native), BGRA[3], RGBA[5]
memory type: DX11(native)

VC-1 decode features
10bit depth:     no
acceleration:    Hardware-accelerated
max streams:     16

VC-1 output:
Width:       32 - 1920
Height:      32 - 1080
alignment:   32
Interlace:   yes
pix format:  NV12[1](native), BGRA[3], RGBA[5]
memory type: DX11(native)


=================================================================

_**VCEEncC64.exe --check-hw**_

VCEEnc (x64) 7.18 (r1319) by rigaya, Dec 21 2022 14:05:10 (VC 1934/Win)
AMF Version 1.4.28
reader: raw, avs, vpy, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP9, VC-1, AV1]
VCE available
device #0: AMD Radeon


=================================================================

**_VCEEncC64.exe --check-encoders_**

aac             : AAC (Advanced Audio Coding)
aac_mf          : AAC via MediaFoundation
ac3             : ATSC A/52A (AC-3)
ac3_fixed       : ATSC A/52A (AC-3)
ac3_mf          : AC3 via MediaFoundation
adpcm_adx       : SEGA CRI ADX ADPCM
adpcm_argo      : ADPCM Argonaut Games
adpcm_ima_alp   : ADPCM IMA High Voltage Software ALP
adpcm_ima_amv   : ADPCM IMA AMV
adpcm_ima_apm   : ADPCM IMA Ubisoft APM
adpcm_ima_qt    : ADPCM IMA QuickTime
adpcm_ima_ssi   : ADPCM IMA Simon & Schuster Interactive
adpcm_ima_wav   : ADPCM IMA WAV
adpcm_ima_ws    : ADPCM IMA Westwood
adpcm_ms        : ADPCM Microsoft
adpcm_swf       : ADPCM Shockwave Flash
adpcm_yamaha    : ADPCM Yamaha
alac            : ALAC (Apple Lossless Audio Codec)
aptx            : aptX (Audio Processing Technology for Bluetooth)
aptx_hd         : aptX HD (Audio Processing Technology for Bluetooth)
ass             : ASS (Advanced SubStation Alpha) subtitle
comfortnoise    : RFC 3389 comfort noise generator
dca             : DCA (DTS Coherent Acoustics)
dvbsub          : DVB subtitles
dvdsub          : DVD subtitles
eac3            : ATSC A/52 E-AC-3
flac            : FLAC (Free Lossless Audio Codec)
g722            : G.722 ADPCM
g723_1          : G.723.1
g726            : G.726 ADPCM
g726le          : G.726 little endian ADPCM ("right-justified")
libmp3lame      : libmp3lame MP3 (MPEG audio layer 3)
libopus         : libopus Opus
libspeex        : libspeex Speex
libtwolame      : libtwolame MP2 (MPEG audio layer 2)
libvorbis       : libvorbis
mlp             : MLP (Meridian Lossless Packing)
mov_text        : 3GPP Timed Text subtitle
mp2             : MP2 (MPEG audio layer 2)
mp2fixed        : MP2 fixed point (MPEG audio layer 2)
mp3_mf          : MP3 via MediaFoundation
nellymoser      : Nellymoser Asao
opus            : Opus
pcm_alaw        : PCM A-law / G.711 A-law
pcm_dvd         : PCM signed 16|20|24-bit big-endian for DVD media
pcm_f32be       : PCM 32-bit floating point big-endian
pcm_f32le       : PCM 32-bit floating point little-endian
pcm_f64be       : PCM 64-bit floating point big-endian
pcm_f64le       : PCM 64-bit floating point little-endian
pcm_mulaw       : PCM mu-law / G.711 mu-law
pcm_s16be       : PCM signed 16-bit big-endian
pcm_s16be_planar: PCM signed 16-bit big-endian planar
pcm_s16le       : PCM signed 16-bit little-endian
pcm_s16le_planar: PCM signed 16-bit little-endian planar
pcm_s24be       : PCM signed 24-bit big-endian
pcm_s24daud     : PCM D-Cinema audio signed 24-bit
pcm_s24le       : PCM signed 24-bit little-endian
pcm_s24le_planar: PCM signed 24-bit little-endian planar
pcm_s32be       : PCM signed 32-bit big-endian
pcm_s32le       : PCM signed 32-bit little-endian
pcm_s32le_planar: PCM signed 32-bit little-endian planar
pcm_s64be       : PCM signed 64-bit big-endian
pcm_s64le       : PCM signed 64-bit little-endian
pcm_s8          : PCM signed 8-bit
pcm_s8_planar   : PCM signed 8-bit planar
pcm_u16be       : PCM unsigned 16-bit big-endian
pcm_u16le       : PCM unsigned 16-bit little-endian
pcm_u24be       : PCM unsigned 24-bit big-endian
pcm_u24le       : PCM unsigned 24-bit little-endian
pcm_u32be       : PCM unsigned 32-bit big-endian
pcm_u32le       : PCM unsigned 32-bit little-endian
pcm_u8          : PCM unsigned 8-bit
pcm_vidc        : PCM Archimedes VIDC
real_144        : RealAudio 1.0 (14.4K)
roq_dpcm        : id RoQ DPCM
s302m           : SMPTE 302M
sbc             : SBC (low-complexity subband codec)
sonic           : Sonic
sonicls         : Sonic lossless
srt             : SubRip subtitle
ssa             : ASS (Advanced SubStation Alpha) subtitle
subrip          : SubRip subtitle
text            : Raw text subtitle
truehd          : TrueHD
tta             : TTA (True Audio)
ttml            : TTML subtitle
vorbis          : Vorbis
wavpack         : WavPack
webvtt          : WebVTT subtitle
wmav1           : Windows Media Audio 1
wmav2           : Windows Media Audio 2
xsub            : DivX subtitles (XSUB)

**Comment by quamt** [comment]
What is the exact model of that LG TV and what is your command line that you are using to convert the files?

**Comment by rigaya** [comment]
I’ll close this issue, as I’ll not be able to fix problem on specific hardware.
