### ISSUE TITLE
HEVC Pre Analysis not working

### ISSUE THREAD

**Issue by GlitterKill** [rigaya/VCEEnc#73]
When trying to encode to HEVC using VCEEnc64 I run into these errors whenever I trye to use Pre Analysis (--pa):

storage->SetProperty(PAActivityType)=0 failed: invalid param..
storage->SetProperty(PACAQStrength)=1 failed: invalid param..
storage->SetProperty(PAHighMotionQualityBoostMode)=0 failed: invalid param..
storage->SetProperty(PALongTermReferenceEnable)=false failed: invalid param..
storage->SetProperty(PALookAheadBufferDepth)=0 failed: invalid param..
storage->SetProperty(PAMaxQPBeforeForceSkip)=35 failed: invalid param..
storage->SetProperty(PAPerceptualAQMode)=0 failed: invalid param..
storage->SetProperty(PASceneChangeDetectionEnable)=true failed: invalid param..
storage->SetProperty(PASceneChangeDetectionSensitivity)=1 failed: invalid param..
storage->SetProperty(PAStaticSceneDetectionEnable)=true failed: invalid param..
storage->SetProperty(PAStaticSceneDetectionSensitivity)=2 failed: invalid param..
storage->SetProperty(PATemporalAQMode)=0 failed: invalid param..
VCEEnc (x64) 7.18 (r1319) by rigaya, Dec 21 2022 14:05:10 (VC 1934/Win)
OS:            Windows 11 x64 (22621) [UTF-8]
CPU:           AMD Ryzen 9 7900X 12-Core Processor [5.53GHz] (12C/24T)
GPU:           AMD Radeon RX 7900 XTX, AMF Runtime 1.4.28 / SDK 1.4.28

**Comment by rigaya** [comment]
[VCEEnc 8.00](https://github.com/rigaya/VCEEnc/releases/tag/8.00) will be able to support --pa with HEVC encoding (8bit).

HEVC 10bit encoding with --pa will still run into different error.

**Comment by rigaya** [comment]
I'll close this issue as Pre Analysis for HEVC should be working fine after VCEEnc 8.00.
