### ISSUE TITLE
Usage of --vpp-enhance together with --avhw, causes green flicker

### ISSUE THREAD

**Issue by quamt** [rigaya/VCEEnc#77]
Hello @rigaya,

When using --vpp-enhance together with --avhw it causes green flicker in the output video.
When using --avsw it does not happen. 

```
VCEEnc (x64) 8.07 (r1403) by rigaya, Feb 28 2023 10:04:38 (VC 1934/Win)
OS:            Windows 11 x64 (22621) [UTF-8]
CPU:           AMD Ryzen 5 5600G with Radeon Graphics [4.32GHz] (6C/12T)
GPU:           AMD Radeon RX 6700 XT, AMF Runtime 1.4.29 / SDK 1.4.29
```

Usage avhw below
```
--avhw  
--codec h264  
--preset slow  
--pa sc=high,ss=high,activity-type=yuv,paq=caq,taq=on,lookahead=32
--vbr 3500  
--vbv-bufsize 10000  
--max-bitrate 5000  
--gop-len 24  
--ref 3 
--bframes 3
--b-pyramid
--vpp-enhance
```

**Comment by rigaya** [comment]
Unfortunately, I were not able to reproduce the issue with the same command line on RX7900XT or RX5500XT with 23.2.2 driver. Might be difficult if it is RX6xxx series specific...

```
OS:            Windows 11 x64 (22621) [UTF-8]
GPU0:           AMD Radeon RX 7900 XT, AMF Runtime 1.4.29 / SDK 1.4.29
GPU2:           Radeon RX 5500 XT, AMF Runtime 1.4.29 / SDK 1.4.29
```

Please try driver update if you have not installed 23.2.2 driver.

**Comment by quamt** [comment]
I checked and I'm up to date with driver 23.2.2.
Would a logfile be of any help?

**Comment by quamt** [comment]
I just let one file convert completely and watched it.
The issue is also in the --avsw.
I might try use DDU to uninstall and reinstall the driver.

**Comment by rigaya** [comment]
I'm afraid log file won't help in this case.

Will it also cause green flicker if you use ```--vpp-preprocess``` instead of ```--vpp-enhance```? (as it goes into the same routinue)

**Comment by quamt** [comment]
I will test and report back.

**Comment by quamt** [comment]
Tested with `--vpp-preprocess` with `--avsw` and `--avhw` and no green flicker seen.

**Comment by quamt** [comment]
I reinstalled the drivers and the green flicker seems to be gone now.
I will monitor and report back if it should reappear.

**Comment by rigaya** [comment]
Nice to hear the green flicker is gone with driver reinstall.

**Comment by quamt** [comment]
Was to early, it is back.
The flickering still occurs.
I even changed  the Graphics settings to use the 6700 XT as preferred for the VCEEnc but doesnt help.
Its very strange.

**Comment by quamt** [comment]
I did some more testing after driver reinstall and the setting mentioned.
It seems that `--pa` is the culprit that causes issues. 
I removed everything and only used the `--vpp-enhance`
Adding the others back, one after the other and once I reached `--pa` it happened.

**Comment by rigaya** [comment]
I see, so something wrong with combination of ```--pa``` and ```--vpp-enhance```.

Furthermore, it's strange as from the application(VCEEncC) side ```--vpp-enhance``` and ```--vpp-preprocess``` is calling the AMF filter in the same way and only ```--vpp-enhance``` causes the issue. I currently have no idea to fix it.

**Comment by quamt** [comment]
The thing is after reinstalling the driver all the AMF extras seem to cause the issue when `--pa` is activated too.
But I was able to see that `--pa` itself creates issues now when it is called without anything else like:

```
--avhw  
--codec h264  
--preset slow 
--pa sc=high,ss=high,activity-type=yuv,paq=caq,taq=on,lookahead=32 
--vbr 20000  
--vbv-bufsize 30000  
--max-bitrate 25000  
--gop-len 24  
```

**Comment by rigaya** [comment]
So it's more about problem with ```--pa```, and may happen to appear more clearly when AMF vpp's are activated.

Setting lookahead to 0 might help, as it had some problem (crushing) in the past driver versions.
```
--pa sc=high,ss=high,activity-type=yuv,paq=caq,taq=on,lookahead=0
```

**Comment by quamt** [comment]
Thank you for the information.
Indeed it is the culprit. Setting it to 0 and the flickering disappears.
Setting only 1 and it reappears again.

**Comment by DimkaTsv** [comment]
Can confirm this issue up to this date. 
But it also happens if --output-res XXXX*XXXX (which is upscaled for me) is applied. 
Because it requests --vpp-resize as mediator functionality. 

Adrenaline 23.7.1... 
Is it VCEEncC specific issue, or should i probably report it to AMD team?

**Comment by DimkaTsv** [comment]
Reported to AMD
Took them some time, but here is their response
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/402

Basically they fixed issue internally and it will roll out publicly in the future.

**Comment by quamt** [comment]
Wow, thank you, @DimkaTsv, for the update.

**Comment by DimkaTsv** [comment]
Hmm... Tried to upscale videos using 23.11.1 driver, both outputs were fine
@quamt Check on your side if issue was resolved.
