### ISSUE TITLE
Usage of --vpp-resize amf_fsr shows sharpness 0.0

### ISSUE THREAD

**Issue by quamt** [rigaya/VCEEnc#78]
Hello @rigaya 

When using `--vpp-resize amf_fsr ` the cmd shows:
`HQscaler: 640x480 -> 1440x1080, fsr, sharpness 0.0`

But couldn't find where/how to controll/adjust the sharpness.

**Comment by DimkaTsv** [comment]
In theory there should be way (as well as option for FSR 2.0. 
**https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/doc/AMF_HQ_Scaler_API.pdf**
In practice - no idea

**Comment by rigaya** [comment]
Although not documented, you can use ```--vpp-scaler-sharpness <float>```, but it seems to not work at this time. I'm not sure if it is a bug in the app or simply not yet supported in AMF.

**Comment by DimkaTsv** [comment]
> I finally found ways to make vpp-scaler-sharpness work fine, it should now have effect on amf_fsr at [VCEEnc 8.19](https://github.com/rigaya/VCEEnc/releases/tag/8.19).

Scalar not applying got fixed some time ago. But to note, this parameter is unique to amf_fsr scalar.
