### ISSUE TITLE
Long file names not supported? 

### ISSUE THREAD

**Issue by quamt** [rigaya/VCEEnc#8]
I am not sure if this is an issue or user problem.

If the filename looks like test.mp4 the de/encoding works but if the filename starts looking like:
This is a file with a long file name to Encode.mp4
An error message pops up that the file does not exist.

Filename is in " anything I missed maybe?

**Comment by rigaya** [comment]
There should be no problem even if the file name is long. For example, command line below works pretty fine.

x64\VCEEncC64.exe -i "Hana - Sakura to kotori Full size 2.mkv" -o "F:\temp\Hana - Sakura to kotori Full size 2 encoded.mp4" --avsw

**Comment by quamt** [comment]
Ok, I will need to check on my side and will report back.
Thank you.

**Comment by quamt** [comment]
Ok, I found the problem.

I tried to execute the program from C:\ and it always showed that problem.
I now copied it to D:\ and it works.
