### ISSUE TITLE
Not an issue more of a question... 

### ISSUE THREAD

**Issue by quamt** [rigaya/VCEEnc#9]
Apologise for this questions as I might not understand the AMF very well. 
Is there any way to have different AMF versions available?

I mean after 5.01 till 6.00 there been a lot of fixes and improvements implemented which version 5.01 doesn't have.
For example: Is it possible to support previous hardware in 6.00 with preanalysis again?
Or will there be issues in regards of compatibility with AMF version if more than one AMF version is used?

**Comment by rigaya** [comment]
> Is there any way to have different AMF versions available?

It might be possible but it would add more complicated codes for that, which I don't want to try.

For pre-analysis, I found that the old "pre-analysis" seems to be renamed to "pre-encode". I have added new option [--pe](https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#--pe) for this in [VCEEnc 6.01](https://github.com/rigaya/VCEEnc/releases/tag/6.01), which might work in previous hardwares.

**Comment by quamt** [comment]
That sounds great.
Thank you :-)
