### ISSUE TITLE
control the deblocking

### ISSUE THREAD

**Issue by Galaxoid-333** [rigaya/VCEEnc#90]
Is it possible to control the deblocking of the VCEEnc H265 version? I compared x264, x265, VCEEnc H264 and VCEEnc H265 for a long time. The conclusion is that VCEEnc H265 removes blocks much worse than anyone else. I didn't find anything on this subject in the AMF documentation.

**Comment by rigaya** [comment]
AMF does not have options to handle deblocking for HEVC at this point. Therefore, there is no way to control the deblocking feature.

**Comment by rigaya** [comment]
I'll close this issue as the question has been answered.
