### ISSUE TITLE
（修正）Aviutl_VCEEnc_7.14以降のバージョンでプロファイルにmain10を指定すると--preset unknownとなる

### ISSUE THREAD

**Issue by doranarasi** [rigaya/VCEEnc#98]
色々と間違えておりましたので、タイトルを含めて修正致します。

Aviutl_VCEEnc_8.16でプロファイルにmain10を使おうとすると、
以下の画像のようにpresetの因数がunknownとなり出力に失敗します。

![スクリーンショット 2023-10-28 164110](https://github.com/rigaya/VCEEnc/assets/6565332/5fa179fd-968c-41fd-b6e0-42525ac473c9)

GUIで以下のように設定しOKを押してAviutlで出力しようとすると発生します。

![スクリーンショット 2023-10-28 162920](https://github.com/rigaya/VCEEnc/assets/6565332/abb980f6-35e7-4903-a40b-e63ca32cd16c)

また、OK押下後にもう一度設定のGUIを開くと、
プロファイルがMain、レベルがautoに勝手に戻ってしまいます。

VCEEncC.exeの方は8.16でも問題なく--preset main10で変換が通りました。
使用GPUはRX6800です。

**Comment by rigaya** [comment]
ご指摘いただきありがとうございました。[VCEEnc 8.17](https://github.com/rigaya/VCEEnc/releases/tag/8.17) で修正いたしました。

**Comment by rigaya** [comment]
修正を実施したため、クローズいたします。
